//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookKeeperWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BookKeeperEntities : DbContext
    {
        public BookKeeperEntities()
            : base("name=BookKeeperEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
        public virtual DbSet<Type> Types { get; set; }
        public virtual DbSet<Transaction1> Transactions1 { get; set; }
        public virtual DbSet<MonthlyTotals> MonthlyTotals { get; set; }
        public virtual DbSet<MonthlyTotalv2> MonthlyTotalv2 { get; set; }
    
        public virtual int GetTransposedView()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetTransposedView");
        }
    
        public virtual ObjectResult<Test1_Result> Test1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Test1_Result>("Test1");
        }
    
        public virtual ObjectResult<GetYearTotals_Result> GetYearTotals()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetYearTotals_Result>("GetYearTotals");
        }
    }
}
